export type FloodLevel = "high" | "medium" | "low";

export type DistrictProfile = {
  id: string;
  name: string;
  hq: string;
  lat: number;
  lon: number;
  population: number; // in thousands (approx)
  floodProneLevel: FloodLevel;
  baseWaterQuality: number; // 0-100, lower = worse
  baseRainfall: number; // mm 24h
  baseTemperature: number; // C
  weather: "rainy" | "cloudy" | "sunny" | "storm";
  activeDiseases: string[];
  /** Stable seed used to generate deterministic synthetic reports per district. */
  reportSeed: number;
};

/**
 * All 35 districts of Assam with approximate centroid coordinates,
 * flood-proneness profile, and seasonal post-flood disease activity.
 *
 * Brahmaputra-belt districts are flagged "high" flood-prone.
 * Barak valley (Cachar, Karimganj, Hailakandi) is medium-to-high.
 * Hill districts (Dima Hasao, Karbi Anglong) are mostly low flood, but
 * landslide and water-source contamination still drives disease risk.
 */
export const DISTRICTS: DistrictProfile[] = [
  {
    id: "baksa",
    name: "Baksa",
    hq: "Mushalpur",
    lat: 26.7,
    lon: 91.5,
    population: 950,
    floodProneLevel: "medium",
    baseWaterQuality: 58,
    baseRainfall: 42,
    baseTemperature: 29,
    weather: "rainy",
    activeDiseases: ["diarrhea", "malaria"],
    reportSeed: 11,
  },
  {
    id: "bajali",
    name: "Bajali",
    hq: "Pathsala",
    lat: 26.55,
    lon: 91.05,
    population: 290,
    floodProneLevel: "medium",
    baseWaterQuality: 55,
    baseRainfall: 48,
    baseTemperature: 30,
    weather: "rainy",
    activeDiseases: ["typhoid", "diarrhea"],
    reportSeed: 7,
  },
  {
    id: "barpeta",
    name: "Barpeta",
    hq: "Barpeta",
    lat: 26.32,
    lon: 91.0,
    population: 1820,
    floodProneLevel: "high",
    baseWaterQuality: 38,
    baseRainfall: 78,
    baseTemperature: 30,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "japanese_encephalitis"],
    reportSeed: 27,
  },
  {
    id: "biswanath",
    name: "Biswanath",
    hq: "Biswanath Chariali",
    lat: 26.7,
    lon: 93.15,
    population: 620,
    floodProneLevel: "high",
    baseWaterQuality: 44,
    baseRainfall: 64,
    baseTemperature: 29,
    weather: "rainy",
    activeDiseases: ["diarrhea", "malaria"],
    reportSeed: 14,
  },
  {
    id: "bongaigaon",
    name: "Bongaigaon",
    hq: "Bongaigaon",
    lat: 26.48,
    lon: 90.55,
    population: 880,
    floodProneLevel: "medium",
    baseWaterQuality: 52,
    baseRainfall: 56,
    baseTemperature: 30,
    weather: "rainy",
    activeDiseases: ["typhoid", "diarrhea"],
    reportSeed: 12,
  },
  {
    id: "cachar",
    name: "Cachar",
    hq: "Silchar",
    lat: 24.83,
    lon: 92.78,
    population: 1900,
    floodProneLevel: "high",
    baseWaterQuality: 36,
    baseRainfall: 84,
    baseTemperature: 31,
    weather: "storm",
    activeDiseases: ["cholera", "leptospirosis", "dengue"],
    reportSeed: 31,
  },
  {
    id: "charaideo",
    name: "Charaideo",
    hq: "Sonari",
    lat: 27.0,
    lon: 95.1,
    population: 480,
    floodProneLevel: "low",
    baseWaterQuality: 68,
    baseRainfall: 28,
    baseTemperature: 27,
    weather: "cloudy",
    activeDiseases: ["malaria"],
    reportSeed: 5,
  },
  {
    id: "chirang",
    name: "Chirang",
    hq: "Kajalgaon",
    lat: 26.65,
    lon: 90.65,
    population: 490,
    floodProneLevel: "medium",
    baseWaterQuality: 56,
    baseRainfall: 46,
    baseTemperature: 29,
    weather: "rainy",
    activeDiseases: ["diarrhea"],
    reportSeed: 8,
  },
  {
    id: "darrang",
    name: "Darrang",
    hq: "Mangaldoi",
    lat: 26.45,
    lon: 92.03,
    population: 980,
    floodProneLevel: "high",
    baseWaterQuality: 41,
    baseRainfall: 71,
    baseTemperature: 30,
    weather: "rainy",
    activeDiseases: ["diarrhea", "japanese_encephalitis"],
    reportSeed: 21,
  },
  {
    id: "dhemaji",
    name: "Dhemaji",
    hq: "Dhemaji",
    lat: 27.48,
    lon: 94.58,
    population: 720,
    floodProneLevel: "high",
    baseWaterQuality: 32,
    baseRainfall: 92,
    baseTemperature: 28,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "malaria"],
    reportSeed: 34,
  },
  {
    id: "dhubri",
    name: "Dhubri",
    hq: "Dhubri",
    lat: 26.02,
    lon: 89.97,
    population: 2100,
    floodProneLevel: "high",
    baseWaterQuality: 30,
    baseRainfall: 86,
    baseTemperature: 31,
    weather: "storm",
    activeDiseases: ["cholera", "typhoid", "hepatitis_a"],
    reportSeed: 38,
  },
  {
    id: "dibrugarh",
    name: "Dibrugarh",
    hq: "Dibrugarh",
    lat: 27.48,
    lon: 94.91,
    population: 1500,
    floodProneLevel: "high",
    baseWaterQuality: 47,
    baseRainfall: 62,
    baseTemperature: 28,
    weather: "rainy",
    activeDiseases: ["dengue", "malaria"],
    reportSeed: 22,
  },
  {
    id: "dima_hasao",
    name: "Dima Hasao",
    hq: "Haflong",
    lat: 25.4,
    lon: 93.0,
    population: 220,
    floodProneLevel: "low",
    baseWaterQuality: 64,
    baseRainfall: 38,
    baseTemperature: 24,
    weather: "cloudy",
    activeDiseases: ["malaria"],
    reportSeed: 4,
  },
  {
    id: "goalpara",
    name: "Goalpara",
    hq: "Goalpara",
    lat: 26.17,
    lon: 90.62,
    population: 1080,
    floodProneLevel: "high",
    baseWaterQuality: 37,
    baseRainfall: 74,
    baseTemperature: 30,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea"],
    reportSeed: 26,
  },
  {
    id: "golaghat",
    name: "Golaghat",
    hq: "Golaghat",
    lat: 26.5,
    lon: 93.97,
    population: 1100,
    floodProneLevel: "medium",
    baseWaterQuality: 51,
    baseRainfall: 54,
    baseTemperature: 29,
    weather: "rainy",
    activeDiseases: ["diarrhea", "japanese_encephalitis"],
    reportSeed: 13,
  },
  {
    id: "hailakandi",
    name: "Hailakandi",
    hq: "Hailakandi",
    lat: 24.68,
    lon: 92.57,
    population: 720,
    floodProneLevel: "medium",
    baseWaterQuality: 45,
    baseRainfall: 68,
    baseTemperature: 31,
    weather: "rainy",
    activeDiseases: ["typhoid", "diarrhea"],
    reportSeed: 15,
  },
  {
    id: "hojai",
    name: "Hojai",
    hq: "Hojai",
    lat: 26.0,
    lon: 92.85,
    population: 940,
    floodProneLevel: "medium",
    baseWaterQuality: 49,
    baseRainfall: 58,
    baseTemperature: 30,
    weather: "cloudy",
    activeDiseases: ["dengue"],
    reportSeed: 11,
  },
  {
    id: "jorhat",
    name: "Jorhat",
    hq: "Jorhat",
    lat: 26.75,
    lon: 94.22,
    population: 1100,
    floodProneLevel: "medium",
    baseWaterQuality: 53,
    baseRainfall: 52,
    baseTemperature: 28,
    weather: "rainy",
    activeDiseases: ["dengue", "malaria"],
    reportSeed: 12,
  },
  {
    id: "kamrup_metro",
    name: "Kamrup Metropolitan",
    hq: "Guwahati",
    lat: 26.18,
    lon: 91.75,
    population: 1280,
    floodProneLevel: "medium",
    baseWaterQuality: 50,
    baseRainfall: 60,
    baseTemperature: 30,
    weather: "rainy",
    activeDiseases: ["dengue", "diarrhea"],
    reportSeed: 18,
  },
  {
    id: "kamrup",
    name: "Kamrup",
    hq: "Amingaon",
    lat: 26.16,
    lon: 91.4,
    population: 1610,
    floodProneLevel: "high",
    baseWaterQuality: 42,
    baseRainfall: 70,
    baseTemperature: 30,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea"],
    reportSeed: 24,
  },
  {
    id: "karbi_anglong",
    name: "Karbi Anglong",
    hq: "Diphu",
    lat: 26.0,
    lon: 93.4,
    population: 960,
    floodProneLevel: "low",
    baseWaterQuality: 62,
    baseRainfall: 36,
    baseTemperature: 26,
    weather: "cloudy",
    activeDiseases: ["malaria"],
    reportSeed: 6,
  },
  {
    id: "karimganj",
    name: "Karimganj",
    hq: "Karimganj",
    lat: 24.87,
    lon: 92.35,
    population: 1230,
    floodProneLevel: "high",
    baseWaterQuality: 39,
    baseRainfall: 80,
    baseTemperature: 31,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "leptospirosis"],
    reportSeed: 28,
  },
  {
    id: "kokrajhar",
    name: "Kokrajhar",
    hq: "Kokrajhar",
    lat: 26.4,
    lon: 90.27,
    population: 890,
    floodProneLevel: "medium",
    baseWaterQuality: 54,
    baseRainfall: 50,
    baseTemperature: 30,
    weather: "rainy",
    activeDiseases: ["diarrhea", "malaria"],
    reportSeed: 13,
  },
  {
    id: "lakhimpur",
    name: "Lakhimpur",
    hq: "North Lakhimpur",
    lat: 27.23,
    lon: 94.1,
    population: 1080,
    floodProneLevel: "high",
    baseWaterQuality: 35,
    baseRainfall: 88,
    baseTemperature: 28,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "japanese_encephalitis"],
    reportSeed: 33,
  },
  {
    id: "majuli",
    name: "Majuli",
    hq: "Garamur",
    lat: 26.95,
    lon: 94.17,
    population: 170,
    floodProneLevel: "high",
    baseWaterQuality: 28,
    baseRainfall: 96,
    baseTemperature: 29,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "skin_infection"],
    reportSeed: 36,
  },
  {
    id: "morigaon",
    name: "Morigaon",
    hq: "Morigaon",
    lat: 26.25,
    lon: 92.34,
    population: 990,
    floodProneLevel: "high",
    baseWaterQuality: 40,
    baseRainfall: 76,
    baseTemperature: 30,
    weather: "storm",
    activeDiseases: ["cholera", "japanese_encephalitis"],
    reportSeed: 25,
  },
  {
    id: "nagaon",
    name: "Nagaon",
    hq: "Nagaon",
    lat: 26.35,
    lon: 92.68,
    population: 2820,
    floodProneLevel: "high",
    baseWaterQuality: 39,
    baseRainfall: 72,
    baseTemperature: 30,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "japanese_encephalitis"],
    reportSeed: 30,
  },
  {
    id: "nalbari",
    name: "Nalbari",
    hq: "Nalbari",
    lat: 26.45,
    lon: 91.43,
    population: 770,
    floodProneLevel: "medium",
    baseWaterQuality: 50,
    baseRainfall: 58,
    baseTemperature: 30,
    weather: "rainy",
    activeDiseases: ["typhoid", "diarrhea"],
    reportSeed: 12,
  },
  {
    id: "sivasagar",
    name: "Sivasagar",
    hq: "Sivasagar",
    lat: 26.98,
    lon: 94.63,
    population: 1150,
    floodProneLevel: "medium",
    baseWaterQuality: 55,
    baseRainfall: 50,
    baseTemperature: 28,
    weather: "rainy",
    activeDiseases: ["dengue", "malaria"],
    reportSeed: 11,
  },
  {
    id: "sonitpur",
    name: "Sonitpur",
    hq: "Tezpur",
    lat: 26.62,
    lon: 92.78,
    population: 1920,
    floodProneLevel: "high",
    baseWaterQuality: 41,
    baseRainfall: 73,
    baseTemperature: 29,
    weather: "storm",
    activeDiseases: ["cholera", "diarrhea", "japanese_encephalitis"],
    reportSeed: 26,
  },
  {
    id: "south_salmara",
    name: "South Salmara-Mankachar",
    hq: "Hatsingimari",
    lat: 25.95,
    lon: 89.85,
    population: 555,
    floodProneLevel: "high",
    baseWaterQuality: 33,
    baseRainfall: 82,
    baseTemperature: 31,
    weather: "storm",
    activeDiseases: ["cholera", "hepatitis_a"],
    reportSeed: 23,
  },
  {
    id: "tamulpur",
    name: "Tamulpur",
    hq: "Tamulpur",
    lat: 26.7,
    lon: 91.65,
    population: 350,
    floodProneLevel: "medium",
    baseWaterQuality: 57,
    baseRainfall: 44,
    baseTemperature: 29,
    weather: "rainy",
    activeDiseases: ["diarrhea"],
    reportSeed: 7,
  },
  {
    id: "tinsukia",
    name: "Tinsukia",
    hq: "Tinsukia",
    lat: 27.5,
    lon: 95.35,
    population: 1330,
    floodProneLevel: "high",
    baseWaterQuality: 46,
    baseRainfall: 66,
    baseTemperature: 27,
    weather: "rainy",
    activeDiseases: ["malaria", "dengue"],
    reportSeed: 19,
  },
  {
    id: "udalguri",
    name: "Udalguri",
    hq: "Udalguri",
    lat: 26.75,
    lon: 92.1,
    population: 830,
    floodProneLevel: "medium",
    baseWaterQuality: 53,
    baseRainfall: 54,
    baseTemperature: 29,
    weather: "rainy",
    activeDiseases: ["diarrhea", "malaria"],
    reportSeed: 14,
  },
  {
    id: "west_karbi_anglong",
    name: "West Karbi Anglong",
    hq: "Hamren",
    lat: 25.93,
    lon: 92.85,
    population: 295,
    floodProneLevel: "low",
    baseWaterQuality: 65,
    baseRainfall: 32,
    baseTemperature: 26,
    weather: "cloudy",
    activeDiseases: ["malaria"],
    reportSeed: 5,
  },
];

export const DISTRICT_BY_ID: Record<string, DistrictProfile> = DISTRICTS.reduce(
  (acc, d) => {
    acc[d.id] = d;
    return acc;
  },
  {} as Record<string, DistrictProfile>,
);

/** Approximate Brahmaputra centerline through Assam — used for the map overlay. */
export const BRAHMAPUTRA_PATH: { lat: number; lon: number }[] = [
  { lat: 27.7, lon: 95.95 },
  { lat: 27.55, lon: 95.4 },
  { lat: 27.5, lon: 94.95 },
  { lat: 27.0, lon: 94.6 },
  { lat: 26.95, lon: 94.2 },
  { lat: 26.8, lon: 93.6 },
  { lat: 26.6, lon: 93.0 },
  { lat: 26.45, lon: 92.5 },
  { lat: 26.3, lon: 92.0 },
  { lat: 26.18, lon: 91.7 },
  { lat: 26.18, lon: 91.3 },
  { lat: 26.15, lon: 90.8 },
  { lat: 26.05, lon: 90.4 },
  { lat: 25.95, lon: 89.95 },
];

export function nearestDistrict(
  lat: number,
  lon: number,
): DistrictProfile {
  let best = DISTRICTS[0]!;
  let bestDist = Number.POSITIVE_INFINITY;
  for (const d of DISTRICTS) {
    const dx = d.lon - lon;
    const dy = d.lat - lat;
    const dist = dx * dx + dy * dy;
    if (dist < bestDist) {
      bestDist = dist;
      best = d;
    }
  }
  return best;
}